In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Karnataka_final.csv')
df.head()

magnitude   yod                                         coordinate   row  \
0  245.614029  2001  {"geodesic":false,"type":"Point","coordinates"...  8626   
1  218.916199  2001  {"geodesic":false,"type":"Point","coordinates"...  8424   
2  624.309326  2001  {"geodesic":false,"type":"Point","coordinates"...  8671   
3  403.655273  2001  {"geodesic":false,"type":"Point","coordinates"...  8637   
4  364.548004  2001  {"geodesic":false,"type":"Point","coordinates"...  8641   

     col  anthrome  prec_2001  prec_2002  prec_2003  prec_2004  ...  \
0  30919        32        796        569        584        955  ...   
1  30861        25        715        671        487        834  ...   
2  30781        32       2184       2005       2020       2362  ...   
3  30894        26        856        636        640        922  ...   
4  30876        26        961        713        736       1053  ...   

   tmean_2005  tmean_2006  tmean_2007  tmean_2008  tmean_2009  tmean_2010  \
0       35973       35945       35948       35917       35956       36006   
1       35826       35817       35818       35758       35828       35866   
2       35537       35532       35540       35513       35556       35584   
3       35966       35940       35946       35913       35952       36001   
4       35778       35757       35763       35727       35768       35816   

   tmean_2011  tmean_2012  tmean_2013  label  
0       35939       36034       36032      0  
1       35782       35884       35875      0  
2       35529       35582       35575      1  
3       35935       36027       36024      0  
4       35747       35836       35837      0  

[5 rows x 50 columns]

In [3]:
y = np.array(df['label'])
df = df.drop(['row','col','coordinate','yod','magnitude', 'label'],axis=1)
print(df.columns)
df.head()

Index(['anthrome', 'prec_2001', 'prec_2002', 'prec_2003', 'prec_2004',
       'prec_2005', 'prec_2006', 'prec_2007', 'prec_2008', 'prec_2009',
       'prec_2010', 'prec_2011', 'prec_2012', 'prec_2013', 'pop_2001',
       'pop_2002', 'pop_2003', 'pop_2004', 'pop_2005', 'pop_2006', 'pop_2007',
       'pop_2008', 'pop_2009', 'pop_2010', 'pop_2011', 'pop_2012', 'pop_2013',
       'Soil_Grid__bdod_mean', 'Soil_Grid__cec_mean', 'Soil_Grid__phh2o_mean',
       'Soil_Grid__soc_mean', 'tmean_2001', 'tmean_2002', 'tmean_2003',
       'tmean_2004', 'tmean_2005', 'tmean_2006', 'tmean_2007', 'tmean_2008',
       'tmean_2009', 'tmean_2010', 'tmean_2011', 'tmean_2012', 'tmean_2013'],
      dtype='object')


anthrome  prec_2001  prec_2002  prec_2003  prec_2004  prec_2005  prec_2006  \
0        32        796        569        584        955       1094        611   
1        25        715        671        487        834       1286        593   
2        32       2184       2005       2020       2362       2098       2506   
3        26        856        636        640        922       1058        671   
4        26        961        713        736       1053       1172        795   

   prec_2007  prec_2008  prec_2009  ...  tmean_2004  tmean_2005  tmean_2006  \
0        856        995        679  ...       35921       35973       35945   
1       1095       1072       1000  ...       35783       35826       35817   
2       2905       2008       2162  ...       35503       35537       35532   
3        880        897        695  ...       35914       35966       35940   
4       1020       1043        800  ...       35730       35778       35757   

   tmean_2007  tmean_2008  tmean_2009  tmean_2010  tmean_2011  tmean_2012  \
0       35948       35917       35956       36006       35939       36034   
1       35818       35758       35828       35866       35782       35884   
2       35540       35513       35556       35584       35529       35582   
3       35946       35913       35952       36001       35935       36027   
4       35763       35727       35768       35816       35747       35836   

   tmean_2013  
0       36032  
1       35875  
2       35575  
3       36024  
4       35837  

[5 rows x 44 columns]

In [21]:
df['pop_2010'].describe()

count    9000.000000
mean        2.577333
std         8.370469
min         0.000000
25%         1.021534
50%         1.454076
75%         2.365457
max       334.441803
Name: pop_2010, dtype: float64

In [4]:
anthrome_dict = {
    255:0,
    11:1,12:1, 22:2, 23:2, 24:2, 25:2, 26:2,
    31:3, 32:3, 33:3, 34:3, 35:3, 41:4, 42:4, 43:4,
    51:5, 52:5, 61:6, 62:6, 63:6,
}
#anthrome_dict[df['anthrome'][0]]

In [5]:
df['anthrome'] = df['anthrome'].apply(lambda x:anthrome_dict[x] )
#df['anthrome_2001'] 

In [12]:
i=0
int(df.values[i][0])

3

In [6]:
from tqdm import tqdm
#X = []
X = np.zeros(( len(df.values[:]) ,13,14))
for i in tqdm(range(len(df.values[:]))):
    X[i,:,0] = df.values[i][1:14] #prec
    X[i,:,1] = df.values[i][14:27] #pop
    X[i,:,2] = df.values[i][31:44] #tmean
    X[i,:,3] = df.values[i][27]
    X[i,:,4] = df.values[i][28]
    X[i,:,5] = df.values[i][29]
    X[i,:,6] = df.values[i][30]
    X[i,:,7+int(df.values[i][0])] = 1
    


100%|█████████████████████████████████████████████████████████████████████████████| 9000/9000 [01:24<00:00, 106.75it/s]


In [16]:
len(X)
X.shape

(9000, 13, 14)

In [7]:
from sklearn.preprocessing import StandardScaler
sc_prec = StandardScaler()
sc_tmean = StandardScaler()
sc_soil = StandardScaler()
sc_pop = StandardScaler()

sc_prec.fit(X[:,:,0])
X[:,:,0] = sc_prec.transform(X[:,:,0])
sc_tmean.fit(X[:,:,2])
X[:,:,2] = sc_tmean.transform(X[:,:,2])
sc_pop.fit(X[:,:,1])
X[:,:,1] = sc_pop.transform(X[:,:,1])
sc_soil.fit(X[:,:,3])
X[:,:,3] = sc_soil.transform(X[:,:,3])
X[:,:,4] = sc_soil.transform(X[:,:,4])
X[:,:,5] = sc_soil.transform(X[:,:,5])
X[:,:,6] = sc_soil.transform(X[:,:,6])

In [27]:
X[1,1,:]

array([-0.17279622, -0.12786129, -0.48601196, -0.09902182,  5.95388374,
       -3.06285834, -2.22797482,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
len(X_train)

7200

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout, Flatten, BatchNormalization, Dense, Input, AveragePooling1D
from tensorflow.keras import Model, Sequential

In [10]:
model = Sequential()
model.add(Conv1D(12, 4, activation="relu",input_shape = (13, 14) ) )
model.add(MaxPooling1D())
model.add(Conv1D(24, 4, activation="relu"))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dropout(0.3))
model.add(Dense(256, activation="relu"))
model.add(Dense(128, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

In [11]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 10, 12)            684       
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 5, 12)             0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 2, 24)             1176      
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 1, 24)             0         
_________________________________________________________________
flatten (Flatten)            (None, 24)                0         
_________________________________________________________________
dropout (Dropout)            (None, 24)                0         
_________________________________________________________________
dense (Dense)                (None, 256)               6

In [12]:
model.fit(X_train, y_train, epochs = 15, batch_size=25 ,shuffle=False,validation_data=(X_test, y_test))

Epoch 1/15
288/288 [==============================] - 4s 4ms/step - loss: 0.2499 - accuracy: 0.9272 - val_loss: 0.1856 - val_accuracy: 0.9528
Epoch 2/15
288/288 [==============================] - 0s 1ms/step - loss: 0.2022 - accuracy: 0.9471 - val_loss: 0.1835 - val_accuracy: 0.9528
Epoch 3/15
288/288 [==============================] - 0s 1ms/step - loss: 0.1971 - accuracy: 0.9471 - val_loss: 0.1834 - val_accuracy: 0.9528
Epoch 4/15
288/288 [==============================] - 0s 1ms/step - loss: 0.1932 - accuracy: 0.9471 - val_loss: 0.1838 - val_accuracy: 0.9528
Epoch 5/15
288/288 [==============================] - 0s 1ms/step - loss: 0.1908 - accuracy: 0.9471 - val_loss: 0.1846 - val_accuracy: 0.9528
Epoch 6/15
288/288 [==============================] - 0s 1ms/step - loss: 0.1911 - accuracy: 0.9471 - val_loss: 0.1819 - val_accuracy: 0.9528
Epoch 7/15
288/288 [==============================] - 0s 1ms/step - loss: 0.1903 - accuracy: 0.9471 - val_loss: 0.1816 - val_accuracy: 0.9528
Epoch 

In [36]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
predictions = model.predict_classes(X_train)

print(confusion_matrix(y_train,predictions))  
print(classification_report(y_train,predictions))  
print(accuracy_score(y_train, predictions))

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[[6838    0]
 [ 362    0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      6838
           1       0.00      0.00      0.00       362

    accuracy                           0.95      7200
   macro avg       0.47      0.50      0.49      7200
weighted avg       0.90      0.95      0.93      7200

0.9497222222222222


c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

In [35]:
predictions = model.predict_classes(X_test)

print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  
print(accuracy_score(y_test, predictions))

[[1715    0]
 [  85    0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98      1715
           1       0.00      0.00      0.00        85

    accuracy                           0.95      1800
   macro avg       0.48      0.50      0.49      1800
weighted avg       0.91      0.95      0.93      1800

0.9527777777777777


c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m